### ISSUE TITLE
[Feature] sklearn 기반 행동 인식 모델 훈련

### ISSUE THREAD

**Issue by Tieck-IT** [Tieck-IT/SelfStudyMonitor#2]
## Description

sklearn 기반 행동 인식 모델 훈련
라벨당 1000장의 데이터셋을 직접 수집했지만, cpu의 성능 한계로 1라벨당 100장씩 샘플링 하여 사용함

## To-Do

- [x] GPU기반 모델 훈련 (후보 : LSTM)
- [x] 훈련에 더 많은 데이터셋 사용

## ETC

1. PyTorch로 구현
2. PyTorch로 구현 실패 시 tf.keras로 구현

**Comment by Tieck-IT** [comment]
데이터 수집 기능 추가
- record at csv (class, timestamp, total blink, bpm, eye coords 32 * 3)

**Comment by Tieck-IT** [comment]
To-do

- [ ] 학습 영상 2시간 수집 및 좌표 추출

bps(초당 눈 깜빡임) , 33개의 좌표 * 3 (x,y,z) = 100

Idea
- [ ] AutoEncoder 기반 clustering

**Comment by Tieck-IT** [comment]
clear
